[application]

# Configure asset directory to fix 406 issues
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "ox"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[serve]
# Address to serve on for development
addr = "127.0.0.1"
# Port to serve on  
port = 8080

