[application]

[web.app]

# HTML title tag content
title = "ox"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "ox"

[serve]
# Address to serve on
addr = "0.0.0.0"
# Port to serve on  
port = 8080
